### ISSUE TITLE
Roads under construction are not displayed

### ISSUE THREAD

**Issue by leonardehrenfried** [stadtnavi/digitransit-ansible#24]
![Screenshot from 2020-05-28 11-34-38](https://user-images.githubusercontent.com/151346/83125022-38d33500-a0d7-11ea-9e78-6bec6b708aed.png)

This is the street in OSM: https://www.openstreetmap.org/way/145661403

**Comment by Beck-berry** [comment]
This is how you expected, right?
![Screenshot_2020-06-01_10-24-53](https://user-images.githubusercontent.com/46535522/83391606-076aaa00-a3f4-11ea-8f1c-532cc284c944.png)

But I do not have the rights to push a new branch.

**Comment by leonardehrenfried** [comment]
You should now have the access.
