### ISSUE TITLE
Merge upstream tilemaker changes

### ISSUE THREAD

**Issue by leonardehrenfried** [stadtnavi/digitransit-ansible#30]
Previously I removed the names of water bodies as they were way too prominent (#17) but upstream has some interesting fixes: they display the names based on the size of the lake/river.

This means that not every puddle shows up on the map which is what we want.

## Acceptance criteria

- Get the latest process-openmaptiles.lua file from upstream and merge their changes. Be careful not to overwrite https://github.com/stadtnavi/digitransit-ansible/commit/3737109ff69d6a7335862bf19b9b4cc7843d80c9
- Check the changes in `config-openmaptiles.json`. This file also configures zoom levels but to be honest I haven't fully understood how it interacts with the lua file. We might need the changes, might  not.

Tips:
- `make tileserver-kreis-boeblingen` (https://www.openstreetmap.org/relation/62721) will give you a larger area to test. Of course computing this will take a while.
- The changes regarding the size of features are quite new. If you are having problems, make sure that you've pulled the latest version of the docker image `lehrenfried/tilemaker`.

**Comment by Beck-berry** [comment]
I merged both files from upstream (71be0984) and ran the tilemaker for Böblingen, but I do not see any water names. Could you check it too?

**Comment by leonardehrenfried** [comment]
Can you play around with these lines: https://github.com/stadtnavi/digitransit-ansible/commit/71be09842e88bfa561cb11ca403117d4cf8313e2#diff-d9bd552f13bfe896d4e593ed296e9e0eR26-R27

**Comment by Beck-berry** [comment]
It was weird that upstream did not modify that, I thought some other setting is missing... But I checked it and: When I set the minzoom of the water names to less than 12, the original issue #17 came back. A bigger one like 16 made all the labels disappear.
Finally I stick with 14!
at zoom level 14:
![Screenshot_2020-06-12_10-49-16](https://user-images.githubusercontent.com/46535522/84484009-72409e80-ac9a-11ea-9aee-e7df263cbb0c.png)
at zoom level 15:
![Screenshot_2020-06-12_10-50-08](https://user-images.githubusercontent.com/46535522/84484061-87b5c880-ac9a-11ea-97ea-e09730ed7c67.png)
at zoom level 16:
![Screenshot_2020-06-12_10-50-43](https://user-images.githubusercontent.com/46535522/84484108-97351180-ac9a-11ea-80f1-d8793db9111b.png)
Looks cool! What do you think?

**Comment by leonardehrenfried** [comment]
What do the tiny lakes to the east of Herrenberg look like?

![image](https://user-images.githubusercontent.com/151346/84484901-af596080-ac9b-11ea-93ac-d134b4ae8728.png)

**Comment by Beck-berry** [comment]
The biggest one, Sommertalweiher gets its name displayed on zoom level 16, but the others won't at all.

And these are rather on the south but
at zoom level 14:
![Screenshot_2020-06-12_11-14-06](https://user-images.githubusercontent.com/46535522/84486562-dd3fa480-ac9d-11ea-8dc8-c435341bd0e9.png)
at zoom level 15:
![Screenshot_2020-06-12_11-12-06](https://user-images.githubusercontent.com/46535522/84486421-b08b8d00-ac9d-11ea-9fda-7620aab00f7b.png)
and at zoom level 16:
![Screenshot_2020-06-12_11-12-36](https://user-images.githubusercontent.com/46535522/84486448-b8e3c800-ac9d-11ea-964e-5855be3dec47.png)

**Comment by leonardehrenfried** [comment]
Ok, nice.

When you make the PR, please change the regional extract to test during the automated build to http://download.geofabrik.de/europe/germany/baden-wuerttemberg/tuebingen-regbez-latest.osm.pbf
as discussed previously.

**Comment by Beck-berry** [comment]
Would it spare some time to only run the build on pull requests and not pushes? Then it should run only once.

**Comment by leonardehrenfried** [comment]
Good idea.

**Comment by leonardehrenfried** [comment]
I've undone the merge of th PR and reopened this ticket because I noticed something: all the rivers are gone.

## Before
![Screenshot from 2020-06-12 14-21-22](https://user-images.githubusercontent.com/151346/84502487-b2af1500-acb8-11ea-8d0e-8e5544576356.png)

## After
![Screenshot from 2020-06-12 14-24-50](https://user-images.githubusercontent.com/151346/84502515-c195c780-acb8-11ea-83c5-baa520c8f4c9.png)

Please bring them back.

Your original work is still on the `water` branch.

**Comment by leonardehrenfried** [comment]
If you have problems building the tiles, please wait for https://github.com/systemed/tilemaker/issues/171

**Comment by Beck-berry** [comment]
The [modifications of this block](https://github.com/stadtnavi/digitransit-ansible/blob/71be09842e88bfa561cb11ca403117d4cf8313e2/roles/tilemaker/templates/process-openmaptiles.lua#L343) causes the rivers to disappear. The other modifications were harmless.

**Comment by Beck-berry** [comment]
I was checking on a stream on the north of Herrenberg, and I don't quite get why they are not displayed since the `waterwayClasses` has the value `stream`... But I added another elseif branch to the above mentioned block and this made it right.
I'm not perfectly satisfied with this solution (it is almost an undone of the upstream modifications) but not yet found another (prettier one). Please check commit ad01635e if it works for you too.

**Comment by leonardehrenfried** [comment]
Hmm, lets park this issue until we have found a better solution and have talked to upstream.

**Comment by Beck-berry** [comment]
I used [your PR](https://github.com/systemed/tilemaker/pull/172), and fix the issue for us too!
