### ISSUE TITLE
Investigate on grey map tiles

### ISSUE THREAD

**Issue by Beck-berry** [stadtnavi/digitransit-ansible#33]
![Screenshot from 2020-06-12 11-42-55](https://user-images.githubusercontent.com/46535522/84493455-1250f480-aca8-11ea-9629-0bc58ce3bf52.png)

**Comment by leonardehrenfried** [comment]
I've isolated the problem to the new version of the docker image of tilemaker that I published this week.

Latest master of tilemaker:
![Screenshot from 2020-06-12 14-45-40](https://user-images.githubusercontent.com/151346/84503999-821caa80-acbb-11ea-82c6-55755a267910.png)

Version 1.6.0:
![Screenshot from 2020-06-12 14-45-40](https://user-images.githubusercontent.com/151346/84504027-8b0d7c00-acbb-11ea-93ae-e03eeeb2c650.png)

**Comment by leonardehrenfried** [comment]
https://github.com/systemed/tilemaker/issues/171

**Comment by leonardehrenfried** [comment]
If you read the linked ticket in tilemaker you can see that it seems a problem with tilemaker.

**Comment by leonardehrenfried** [comment]
So here is the task:

- Read https://github.com/systemed/tilemaker/issues/171#issuecomment-643302038
- Clone the tilemaker repository and build a docker container from the latest master (`docker build . -t tilemaker-broken` for example)
- Modify the Makefile in digitransit-ansible to use the broken, local version of tilemaker to build the tiles (https://github.com/stadtnavi/digitransit-ansible/blob/master/Makefile#L41, change `lehrenfried/tilemaker` to `tilemaker-broken`)
- Build the tiles and start the map server with `make tileserver-herrenberg`
- Check that you see the grey map tile
- Modify the lua script to take the OSM id and write it into the tiles file
- Install [vt2geojson](https://github.com/mapbox/vt2geojson)
- Convert the the problematic map tile to GeoJSON with the following command:
