### ISSUE TITLE
Construction sites are too prominent in satellite mode

### ISSUE THREAD

**Issue by leonardehrenfried** [stadtnavi/digitransit-ansible#35]
When you switch to the satellite map mode you can see that construction sites, tunnels and probably a few other types of roads, are too prominent.

![Screenshot from 2020-07-06 12-39-43](https://user-images.githubusercontent.com/151346/86584892-e3b3fa00-bf85-11ea-8982-d86dd865a47f.png)

This is not a OSM extraction issue but a problem with the map style in the file `roles/tileserver-gl/templates/satellite-overlay.json`.

Please check the tunnel and construction site style elements and adjust the opacity to match the rest of the roads.

**Comment by meromisi** [comment]
I set the opacity for the constructions in the city center, but the difference will only be visible when it's on staging and the satellite map layer will be under the street layer. The right one is a tunnel, and it is built by 2 layers on top of each other. The lower layer has stronger color and with increased opacity the lower layer was always prominent. As I mentioned they are tunnels and I checked google maps they just simply hid it as you can see in the picture, so I set the visibility to "none" but on a high zoom level you can see arrow that indicates the direction of the way. 

Before setting the opacity:
![image](https://user-images.githubusercontent.com/54352878/86909235-0bd36280-c118-11ea-9236-ac0ad8f25f39.png)

Lower layer of the tunnel:
![image](https://user-images.githubusercontent.com/54352878/86909061-d3cc1f80-c117-11ea-8a62-b6785cac2e0b.png)

Google maps:
![Screenshot_2020-07-08_12-41-06](https://user-images.githubusercontent.com/54352878/86909470-6bca0900-c118-11ea-9bef-f288f1d673b2.png)

My solution:
![Screenshot_2020-07-08_12-43-00](https://user-images.githubusercontent.com/54352878/86909586-96b45d00-c118-11ea-9b9f-f3bb160429d2.png)

**Comment by leonardehrenfried** [comment]
I actually quite like this display:

![image](https://user-images.githubusercontent.com/151346/86913722-53112180-c11f-11ea-9835-8f790b4c3b12.png)

Is that possible for the tunnel?

And can you open a WIP PR?
