### ISSUE TITLE
Photon/nominatim upgrade plan

### ISSUE THREAD

**Issue by leonardehrenfried** [stadtnavi/digitransit-ansible#43]
We need to get started with the nominatim and photon upgrades. I'm going to summarise the installation process here since there are quite a few steps required.

## Nominatim
- Use standard nominatim 3.7
- Configure the the extra-tags import style with the following addition
```
{   "keys" : ["public_transport"],
    "values" : {
       "platform" : "main,fallback,with_name",
       "stop_position" : "main,fallback,with_name",
       "station" : "main,fallback,with_name"
    }
},
```
- Initial nominatim import
- Download `https://data.mfdz.de/mfdz/nvbw_osm_matches.csv.gz`
- Import CSV stop data with `./nominatim_add_ifopt.py -i osm-nvbw-stop-matches.csv` (with invalidate)
- Nightly import run `./nominatim_add_ifopt.py osm-nvbw-stop-matches.csv` (no invalidate!)

## Photon

- use current komoot/master with two PRs merged in:
  - https://github.com/komoot/photon/pull/581
  - https://github.com/komoot/photon/pull/580
- start up Photon with the flag `-extra-tags ref:IFOPT` 
- run regular import
- start Photon with `-synonym-file`

Did I miss something?

@lonvia @hbruch

**Comment by lonvia** [comment]
The required IFOPT file is now: `https://data.mfdz.de/mfdz/nvbw_osm_matches.csv.gz`.

For the Photon can you currently please use #580 with #581 merged in instead of merging both to master. I did a couple of conflict-inducing changes on master which I'm in the process of resolving.
