### ISSUE TITLE
Matomo Update

### ISSUE THREAD

**Issue by hbruch** [stadtnavi/digitransit-ansible#60]
Matomo should be updated to a [current stable version](https://github.com/matomo-org/matomo/tags) (currently 5.1.2).

Currently, Matomo is deployed via docker image [matomo:4.3-fpm-alpine](https://github.com/stadtnavi/digitransit-ansible/blob/master/roles/matomo/templates/docker-compose.yml#L21C11-L21C33)

This should be updated to a current version.

Historical data should be migrated.

Please extract image tags to variables which can be set independently for different environments, to allow a step by step migration.

**Comment by leonardehrenfried** [comment]
Dev and prod are now upgraded to 5.1.2 and their data was migrated.

For future reference, here are the migration commands:

```
docker exec -it matomo_app_1 /bin/sh
php /var/www/html/console core:update
```

**Comment by hbruch** [comment]
Thanks. As a result, matomo is updated inside the container? Should the ansible script be updated as well?

**Comment by hbruch** [comment]
Thanks. Please document the steps which need to be done in a short "How to update matomo" subsection.
