### ISSUE TITLE
Enhance GTFS by CO2 emissions

### ISSUE THREAD

**Issue by hbruch** [stadtnavi/digitransit-ansible#61]
OpenTripPlanner supports calculating CO2 emissions per itinerary via sandbox plugin [emissions](https://docs.opentripplanner.org/en/latest/sandbox/Emissions/).

It requires a custom extension to the hbg6 GTFS-File, which for every route defines `avg_co2_per_vehicle_per_km` and `avg_passenger_count`_

```
route_id,avg_co2_per_vehicle_per_km,avg_passenger_count
1234,123,20
2345,0,0
3456,12.3,20.0
```

[GTFS-hub](https://github.com/mfdz/gtfs-hub) should be extended to generate such an emissions.txt and add it to the gtfs feed. 

The specific values to be added will be provided by Herrenberg. The local transport agency's  service [Umweltrechner](https://www.vvs.de/umweltrechner) states in the FAQ:
> 
> Berechnung CO2-Ausstoß öffentlicher Verkehrsmittel
> Der Anteil der öffentlichen Verkehrsmittel wird nach ihrem Anteil an der Strecke gewichtet. Bei der Berechnung für die verschiedenen Verkehrsmittel wurden alle jeweiligen Kraftstoffe berücksichtigt – z.B. auch ein geringer Anteil von dieselbetriebenen Bahnen bei der Regionalbahn.
> Quelle CO2-Austoß bei Regionalbahnen und Bussen: [Umweltbundesamt, TREMOD 6.16 (11/2020), Bezugsjahr 2019](https://www.umweltbundesamt.de/themen/verkehr-laerm/emissionsdaten#TREMOD).
> Zudem liegt bei der Berechnung des CO2-Austoßes bei der Regionalbahn der Deutschland-Strommix 2019 zu Grunde.
> Hinweis Berechnung CO2-Austoß Stadtbahn:
> Rechnerisch mit CO2-Emissionswert für Ökostrom aus Wasserkraft von 2,7 g/kWh (Quelle: Umweltbundesamt) und unter Berücksichtigung der Auslastung für Stadtbahnen (Quelle: VDV, Statistik 2019).
> Hinweis Berechnung CO2-Ausstoß S-Bahn: Erläuterungen zur Herleitung von Emmisionsfaktoren, der spezifische Energieverbräuche nach Betriebsarten, Zuggattungen und Streckenhöchstgeschwindigkeiten der DB sowie bezüglich der Auslastung sind im Grundlagenbericht des UmweltMobilChecks enthalten:
> [Zum Grundlagenbericht des UmweltMobilChecks](https://co2kompass.bahn.de/Grundlagenbericht_CO2Kompass_1.1.pdf).
> 
> Art | Gramm CO2 / Personenkilometer
> -- | --
> R-Bahn | 54 g CO2 / km 
> S-Bahn |  37.7 g CO2 / km
> Stadtbahn |  2.6 g CO2 / km
> Bus | 85 g CO2 / km

**Comment by hbruch** [comment]
The feed https://gtfs.mfdz.de/hbg6.merged.with_flex.gtfs.zip now contains an emissions.txt file which is generated by gtfs-hub. 
The script is documented and high-level instructions added to the Datenquellen document. 

@stadtnavimanager please check and close.

**Comment by stadtnavimanager** [comment]
@hbruch I don't have a closing option here. Maybe I am missing the rights?
Could you clode for me please?

**Comment by stadtnavimanager** [comment]
@hbruch please check with the Mail by VVS (Monday, 02.12., 16:27) if we have to adapt our calculation of the CO2-emissions
