### ISSUE TITLE
Make pilot.mobil-in-herrenberg.de also a Debian 10 system

### ISSUE THREAD

**Issue by leonardehrenfried** [stadtnavi/digitransit-ansible#9]
Whilst rolling out to production, a had to make changes to the ansible roles to make them compatible with Ubuntu 18.04, as the staging server is running Debian 10.

Whilst the changes are easy to do, it really defeats the point of a staging system, if they run different operation systems. We really should not find out on the production server, if a change is incompatible.

Acceptance criteria:

- Change the production system to use Debian 10

**Comment by hbruch** [comment]
Production system moved, so closing this issue
